baseUrl: "https://aryndam9.github.io/"
languageCode: en-us
theme: terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true
  # favicon
  favicon: neural.ico
  showLastUpdate: true
  updatedDatePrefix: Modified


languages:
  en:
    languageName: English
    title: Arindam Ghosh
    subtitle: Get more info about Arindam
    keywords: ''
    copyright: Arindam
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page

    params:
      logo:
        logoBlink: '>_'
        logoText: Arindam Ghosh
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: showcase
        name: Showcase
        url: /showcase
